In [ ]:
# 5.	Write a python Program for Bidirectional Associative Memory with 
#     two pairs of vectors.is it correct for this ps

In [1]:

import numpy as np
x1=np.array([1,1,1])
y1=np.array([-1,-1,-1,-1,-1])

x2=np.array([-1,-1,-1])
y2=np.array([1,1,1,1,1])

w=np.outer(x1,y1)+np.outer(x2,y2)

print("weight matrix is:")
print(w)
def step(x):
    return np.where( x>=0,1,-1)

def reacll_y(x_input):
    y=step(np.dot(x_input,w))
    return y



def reacll_x(y_input):
    x=step(np.dot(y_input,w.T))
    return x

input_x=np.array([-1,-1,-1])
print("input given x:",input_x)
print("reacalled y is:")
print(reacll_y(input_x))

input_y=np.array([-1,-1,-1,-1,-1])
print("input given y:",input_y)
print("reacalled x is:")
print(reacll_x(input_y))


weight matrix is:
[[-2 -2 -2 -2 -2]
 [-2 -2 -2 -2 -2]
 [-2 -2 -2 -2 -2]]
input given x: [-1 -1 -1]
reacalled y is:
[1 1 1 1 1]
input given y: [-1 -1 -1 -1 -1]
reacalled x is:
[1 1 1]
