In [17]:
# 8.Write a python program to design a Hopfield Network which stores 4 vectors

In [18]:
#hopfield neural network
import numpy as np

def step(x):
    return np.where(x>=0,1,-1)

    
pattern=np.array([
    [1, 1, -1, -1],
    [1, -1, 1, -1],
    [-1, 1, -1, 1],
    [-1, -1, 1, 1]
])
#weights and bias
n=pattern.shape[1]
w=np.zeros((n,n))

for p in pattern:
    w+= np.outer(p,p)
np.fill_diagonal(w,0)
print("weight matrix is")
print(w)

def hopfield_recall(input_pattern,w,steps=5):
    x=input_pattern
    for i in range(steps):
        x=step(np.dot(w,x))
    return x
test_input=np.array([-1, 1, 1, -1])
output=hopfield_recall(test_input,w)
print("given blured pattern")
print(test_input)
print("identified associated pattern")
print(output)

    

weight matrix is
[[ 0.  0.  0. -4.]
 [ 0.  0. -4.  0.]
 [ 0. -4.  0.  0.]
 [-4.  0.  0.  0.]]
given blured pattern
[-1  1  1 -1]
identified associated pattern
[ 1 -1 -1  1]
